# Generated by Django 4.2.4 on 2023-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_there', models.BooleanField(default=True)),
                ('quality', models.CharField(choices=[('n', 'New'), ('o', 'Old')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
